### ISSUE TITLE
Team Tasks/Checklist

### ISSUE THREAD

**Issue by AniCricKet** [AniCricKet/tmv4#5]
Our Sub-team Sections for the project: 

- [ ] SASS Tutorial Part 1 (topics to cover: themes and layouts) 
**Assigned to:** @nsk1207 @AniCricKet 
- [ ] Tutorial Page  2 (topics to cover: formatting, how frontend connects to backend work) 
**Assigned to:** @chewyboba10 @mmaxwu 
- [ ] Building a javascript game and explaining to students 
**Assigned to:** @RyanHaki @raisinbran25 
- [ ] Creating hacks/homework assignment 
**Assigned to:** @kalanicabralomana
